### ISSUE TITLE
Getting the error "Unsupported data type"

### ISSUE THREAD

**Issue by wecloudheroes** [MicrosoftLearning/mslearn-openai#23]
# Module: 00
#### Step: 00

Description of issue

Repro steps:

getting error in  python executing.
\Labfiles\02-nlp-azure-openai\Python\test-openai-model.py

 print("Summary: " + response.choices[0].message.content + "\n")

1.
1.
1.

**Comment by ivorb** [comment]
Hi @wecloudheroes could you please post the error you're seeing? Are you seeing this in the hosted VM, or on your machine? Due to configuration differences, we're not able to diagnose all issues if running on your machine; if you provide the error or screenshot of the error on a VM I'll do my best to repro and fix

**Comment by ivorb** [comment]
Closing due to no response.
