### ISSUE TITLE
Unable to copy user message in terminal

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/mslearn-openai#78]
## Lab/Demo: Utilize prompt engineering in your app

Step: Run your application (after updating code)
Issue: every "User message" that has a break line, is not processed correctly.

![image](https://github.com/MicrosoftLearning/mslearn-openai/assets/53346841/921a1608-3730-4035-a843-214b4ab65e92)

**Comment by ivorb** [comment]
Can you try copy and pasting from the prompt window on the right into the terminal? Might just be an oddity of how the environment works. The alternative is make that a very long string that doesn't display well

**Comment by ivorb** [comment]
closing due to lack of response. I imagine this is due to the hosted VM experience

**Comment by massimobonanni** [comment]
Hi @ivorb the issue happens because the prompt in the instructions contains linefeed chars. When the standard input receive the line feed, the code continue and only the first line is send to the application.
If they copy the prompt from the instructions to notepad and remove the line feed for each line, it works.
Or we need to find a way to write the prompt in the instructions without the linefeed at the end of each line.

**Comment by ivorb** [comment]
@massimobonanni the linefeed is put in by the hosted environment for multi-line input blocks, not something I have control over in the instructions. If I put it on one line, it makes it quite hard for students to read. I'll play around with other possibilities to improve this experience

**Comment by massimobonanni** [comment]
We can add a note to tell the student to be careful with the multiline

**Comment by ivorb** [comment]
Agreed, I'll do that at least if a different solution doesn't solve it
