### ISSUE TITLE
Default deployment name for images changed to "dall-e-3"

### ISSUE THREAD

**Issue by 1amitn** [MicrosoftLearning/mslearn-openai#85]
# Module: 05
## Lab/Demo: 05

Description of issue
Labfiles/05-image-generation/Python/generate-image.py
The url (line 19) is hard coded with deployment name:
`url = "{}openai/deployments//images/generations?api-version={}".format(api_base, api_version)`
The default name is now "dall-e-3".
Recommended to configure as variable as in other labs or to replace in the code from "dalle3" to "dall-e-3".

Repro steps:
1. go to Labfiles/05-image-generation/Python/generate-image.py
2. modify line 19

Suggested fix with variable:
1. In the .env add "AZURE_OAI_DEPLOYMENT=<placeholder>"
2. In the generate-image.py, under 
```
def main(): 
        try:
        # Get Azure OpenAI Service settings
        load_dotenv()
        api_base = os.getenv("AZURE_OAI_ENDPOINT")
        api_version = '2024-02-15-preview'" 
```
 add "azure_oai_deployment = os.getenv("AZURE_OAI_DEPLOYMENT")"

Update the url to call the DALL-E model:
`url = "{}openai/deployments/{}/images/generations?api-version={}".format(api_base, azure_oai_deployment, api_version)`

**Comment by ivorb** [comment]
While the default name is `dall-e-3`, we specify during deployment to name it `dalle3`, which would make the code work as written. You can see the specified name here:
https://github.com/MicrosoftLearning/mslearn-openai/blob/64e0192c9629f59e3b80a84e5cdf78cc03b2a583/Instructions/Exercises/05-generate-images.md?plain=1#L31

Since code works as written, closing the issue. I'll consider adding it as a variable or changing the code to use the default name.
